Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Admin/UserViewModel.cs
using BMI.Production.DAL.Models;
using System.Collections.Generic;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Admin
{
    public class UserViewModel
    {
        public UserViewModel(string userId, IEnumerable<BmiLog> bmiLogs)
        {
            UserId = userId;
            BmiLogs = bmiLogs;
        }

        public string UserId { get; set; }

        public IEnumerable<BmiLog> BmiLogs { get; set; }
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Admin/UsersViewModel.cs
using BMI.Production.DAL.Models;
using System.Collections.Generic;
using System.Linq;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Admin
{
    public class UsersViewModel
    {
        #region properties
        public List<BmiUser> AllUsers { get; set; } = new List<BmiUser>();
        public List<BmiUser> AllCoaches { get; set; } = new List<BmiUser>();
        public List<BmiUser> AllUsersAndCoaches { get; set; } = new List<BmiUser>();
        #endregion

        #region Methods
        public int AllUsersCount() => AllUsers.Count() + AllCoaches.Count() + AllUsersAndCoaches.Count();
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Coach/AuthRequestViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Coach
{
    public class AuthRequestViewModel
    {
        [Display(Name = "Email of the requested user: ")]
        public string EmailOfRequested { get; set; }
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Coach/DetailBmiLogOfUserViewModel.cs
using BMI.Production.DAL.Models;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Coach
{
    public class DetailBmiLogOfUserViewModel
    {
        #region constructor
        public DetailBmiLogOfUserViewModel(string idUser, BmiLog bmiLog)
        {
            IdUser = idUser;
            BmiLog = bmiLog;
        }
        #endregion

        #region properties
        public string IdUser { get; set; }

        public BmiLog BmiLog { get; set; }
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Coach/RequestCoachViewModel.cs
using BMI.Production.DAL.Models;
using System.Collections.Generic;
using System.Linq;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Coach
{
    public class RequestCoachViewModel
    {
        #region constructors
        public RequestCoachViewModel(string user, IEnumerable<AuthorizedID> acceptedRequests, IEnumerable<AuthorizedID> failedPendingRequest)
        {
            UserId = user;
            AcceptedRequests = acceptedRequests;
            FailedPendingRequest = failedPendingRequest;
        }
        #endregion

        #region properties
        public string UserId { get; set; }
        public IEnumerable<AuthorizedID> AcceptedRequests { get; set; }
        public IEnumerable<AuthorizedID> FailedPendingRequest { get; set; }
        #endregion

        #region methods
        public int CountAllRequest()
        {
            return AcceptedRequests.Count() + FailedPendingRequest.Count();
        }
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Coach/RequestViewModel.cs
using BMI.Production.DAL.Models;
using System.Collections.Generic;
using System.Linq;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Coach
{
    public class RequestViewModel
    {
        #region constructors
        public RequestViewModel(IEnumerable<AuthorizedID> acceptedRequests, IEnumerable<AuthorizedID> failedPendingRequest)
        {
            AcceptedRequests = acceptedRequests;
            FailedPendingRequest = failedPendingRequest;
        }
        #endregion

        #region properties
        public IEnumerable<AuthorizedID> AcceptedRequests { get; set; }
        public IEnumerable<AuthorizedID> FailedPendingRequest { get; set; }
        #endregion

        #region methods
        public int CountAllRequest()
        {
            return AcceptedRequests.Count() + FailedPendingRequest.Count();
        }
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/ViewModels/Coach/UserViewViewModel.cs
using BMI.Production.DAL.Models;
using System.Collections.Generic;

namespace BMI.Production.SqlLite.WebApp.ViewModels.Coach
{
    public class UserViewViewModel
    {
        public UserViewViewModel(IEnumerable<BmiLog> bmiLogs, string userId)
        {
            BmiLogs = bmiLogs;
            UserId = userId;
        }

        public IEnumerable<BmiLog> BmiLogs { get; set; }

        public string UserId { get; set; }
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/Controllers/CoachController.cs
using BMI.Production.DAL.Classes;
using BMI.Production.DAL.Enums;
using BMI.Production.DAL.Interfaces;
using BMI.Production.DAL.Models;
using BMI.Production.SqlLite.WebApp.Interfaces;
using BMI.Production.SqlLite.WebApp.ViewModels.Coach;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BMI.Production.SqlLite.WebApp.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Coach)]
    [Authorize(Policy = "MustBeSignedIn")]
    public class CoachController : Controller, IIdentifierController
    {
        #region fields
        private readonly IBmiRepo _repo;
        private readonly UserManager<BmiUser> _userManager;
        private readonly ILogger<CoachController> _logger;
        #endregion

        #region User Info
        [Authorize(Policy = "MustBeSignedIn")]
        public string UserId() => User.FindFirstValue(ClaimTypes.NameIdentifier);

        [Authorize(Policy = "MustBeSignedIn")]
        public string UserEmail() => User.FindFirstValue(ClaimTypes.Email);

        [Authorize(Policy = "MustBeSignedIn")]
        public string UserRole() => User.FindFirstValue(ClaimTypes.Role);
        #endregion

        #region constructors
        public CoachController(IBmiRepo repo, UserManager<BmiUser> userManager, ILogger<CoachController> logger)
        {
            _repo = repo;
            _userManager = userManager;
            _logger = logger;
        }
        #endregion

        #region HttpGet - Coach
        [HttpGet]
        public IActionResult Index()
        {
            string userId = UserId();
            IEnumerable<AuthorizedID> requests = _repo.GetAuthRequestFromCoach(userId);
            RequestViewModel requestViewModel = new RequestViewModel(requests.Where(auth => auth.StatusRequest == Status.Accepted),
                requests.Where(auth => auth.StatusRequest != Status.Accepted));
            return View(requestViewModel);
        }

        [HttpGet]
        public IActionResult MakeRequest()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> RemoveAuth(string userId)
        {
            BmiUser person = await _userManager.FindByIdAsync(userId) ?? throw new ArgumentNullException();
            return View(person);
        }

        [HttpGet]
        public IActionResult UserView(string userId)
        {
            IEnumerable<BmiLog> bmiLogs = _repo.GetBmiLogsByUser(userId) ?? throw new ArgumentNullException();
            UserViewViewModel userViewViewModel = new UserViewViewModel(bmiLogs, userId);
            return View(userViewViewModel);
        }

        [HttpGet]
        public IActionResult DetailBmiLogOfUser(string userId, int bmiLogId)
        {
            string coachId = UserId();
            AuthorizedID authorizedID = _repo.GetSpecificAuthRequest(coachId, userId);
            if (authorizedID != null)
            {
                BmiLog bmiLogUser = _repo.GetBmiLog(authorizedID.IdUser, bmiLogId);
                string IdUser = _repo.GetById(userId).Id;
                return View(new DetailBmiLogOfUserViewModel(IdUser, bmiLogUser));
            }
            return RedirectToAction("Index", "Coach");
        }
        #endregion

        #region HttpPost - Coach
        [HttpPost]
        public async Task<IActionResult> MakeRequest(AuthRequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                BmiUser person = await _userManager.FindByEmailAsync(model.EmailOfRequested);
                if(person != null)
                {
                    if (_userManager.IsInRoleAsync(person, Roles.Person).Result && person.Id != UserId())
                    {
                        AuthorizedID sendAuthRequest = _repo.CreateAuth(UserId(), person.Id);
                        if (sendAuthRequest != null)
                        {
                            _repo.CreateAuthHistoryInsert(sendAuthRequest.ID, UserId());
                            return RedirectToAction("Index", "Coach");
                        }
                        ModelState.AddModelError(string.Empty, "Could not send an request to get authorization.");
                        _logger.LogError(string.Empty, "Could not send an request to get authorization.");
                    }
                }
                ModelState.AddModelError(string.Empty, "Could not send an request because the user doens't exist or was not in the role of person.");
                _logger.LogError(string.Empty, "Could not send an request because the user doens't exist or was not in the role of person.");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult RemoveAuthUser(BmiUser user)
        {
            if (!string.IsNullOrEmpty(user.Id))
            {
                string coachId = UserId();
                AuthorizedID removedAuthRequest = _repo.DeleteAuthRequest(coachId, user.Id);
                if (removedAuthRequest != null)
                {
                    return RedirectToAction("Index", "Coach");
                }
                _logger.LogError(string.Empty, "Could not delete authorization to an user account");
            }
            return RedirectToAction("Index", "Coach");
        }
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/Controllers/ExportController.cs
using BMI.Production.DAL.Classes;
using BMI.Production.DAL.Interfaces;
using BMI.Production.DAL.Models;
using BMI.Production.SqlLite.WebApp.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace BMI.Production.SqlLite.WebApp.Controllers
{
    [Authorize(Roles = Roles.Coach + "," + Roles.Admin + "," + Roles.Person)]
    [Authorize(Policy = "MustBeSignedIn")]
    public class ExportController : Controller, IIdentifierController
    {
        #region fields
        private readonly IBmiRepo _repo;
        #endregion

        #region User Info
        [Authorize(Policy = "MustBeSignedIn")]
        public string UserId() => User.FindFirstValue(ClaimTypes.NameIdentifier);

        [Authorize(Policy = "MustBeSignedIn")]
        public string UserEmail() => User.FindFirstValue(ClaimTypes.Email);

        [Authorize(Policy = "MustBeSignedIn")]
        public string UserRole() => User.FindFirstValue(ClaimTypes.Role);
        #endregion

        #region constructors
        public ExportController(IBmiRepo repo)
        {
            _repo = repo;
        }
        #endregion

        #region methods
        /**
         * For the 2 export functions I implement a check on the role of the coach to prevent abuse, because for user they get 
         * their data with their user id and with the admin he is allowed almost everything. But the coach is controlled if 
         * he contains the user id he has send through.
         * **/
        [HttpGet]
        public FileResult ReturnCsv(string userId)
        {
            if(UserRole() == Roles.Coach)
            {
                AuthorizedID auth = _repo.GetSpecificAuthRequest(UserId(), userId);
                if (auth == null)
                {
                    return null;
                }
            }
            SetupUserId(ref userId);
            IEnumerable<BmiLog> bmiLogs = _repo.GetBmiLogsByUser(userId) ?? throw new ArgumentNullException();
            return File(bmiLogs.ToList().ReturnCsvList().ByteEncoder(), "text/csv", "logs.csv");
        }

        [HttpGet]
        public FileResult ReturnMd(string userId)
        {
            if (UserRole() == Roles.Coach)
            {
                AuthorizedID auth = _repo.GetSpecificAuthRequest(UserId(), userId);
                if (auth == null)
                {
                    return null;
                }
            }
            SetupUserId(ref userId);
            IEnumerable<BmiLog> bmiLogs = _repo.GetBmiLogsByUser(userId) ?? throw new ArgumentNullException();
            return File(bmiLogs.ToList().ReturnMarkdownList().ByteEncoder(), "text/md", "logs.md");
        }
        #endregion

        #region Setup User Id
        public void SetupUserId(ref string userId)
        {
            if (User.IsInRole(Roles.Person) || userId == null)
                userId = UserId();
        }
        #endregion
    }
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/Views/Coach/DetailBmiLogOfUser.cshtml
@model DetailBmiLogOfUserViewModel;
@inject IBmiRepo BmiRepo;
@{
    ViewData["Title"] = "Bmi log of user";
}

<h1>Bmi log of @BmiRepo.GetById(Model.IdUser).Email</h1>

<div>
    <h4>BmiLog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BmiLog.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BmiLog.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BmiLog.DateLog)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BmiLog.DateLog)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BmiLog.Lenght)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BmiLog.Lenght)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BmiLog.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BmiLog.Weight)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="@User.FindFirstValue(ClaimTypes.Role)" class="btn btn-primary">Back to List</a>
</div>

Bmi.Solution/BMI.Production.SqlLite.WebApp/Views/Coach/Index.cshtml
@model RequestViewModel;
@inject IBmiRepo repo;

<h1>Users that received the authentication requests.</h1>

@if (Model.CountAllRequest() > 0)
{
    if (Model.AcceptedRequests.Count() > 0)
    {
        <h2>Accepted request</h2>
        <table class="table row-cols-sm-3">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Email User</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (AuthorizedID auth in Model.AcceptedRequests)
                {
                    BmiUser ps = repo.GetById(auth.IdUser);
                    <tr>
                        <th>@auth.IdUser</th>
                        <th>
                            <a asp-controller="Coach" asp-action="UserView"
                               asp-route-userId="@auth.IdUser" class="btn-link">@ps.Email</a>
                        </th>
                        <th>
                            <a asp-controller="Coach" asp-action="RemoveAuth"
                               asp-route-userId="@auth.IdUser" class="btn-link">Remove Authorization</a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    if (Model.FailedPendingRequest.Count() > 0)
    {
        <h2>Failed and pending requests</h2>
        <table class="table row-cols-sm-3">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Email User</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (AuthorizedID auth in Model.FailedPendingRequest)
                {
                    BmiUser ps = repo.GetById(auth.IdUser);
                    <tr>
                        <th>@auth.IdUser</th>
                        <th>
                            @ps.Email
                        </th>
                        <th>
                            <a asp-controller="Coach" asp-action="RemoveAuth"
                               asp-route-userId="@auth.IdUser" class="btn-link">Remove Authorization</a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    @section Scripts{
        <script>
            $('#accordeonAuth').collapse({
                toggle: false
            });
        </script>
    }
}
else
{
    <h2 class="text-center">You have no Users that accepted you're authorization request.</h2>
}

Bmi.Solution/BMI.Production.SqlLite.WebApp/Views/Coach/MakeRequest.cshtml
@model AuthRequestViewModel

@{
    ViewData["Title"] = "Make Request";
}

<h1>Make authorization request</h1>

<div class="row">
    <form asp-action="MakeRequest" asp-controller="Coach" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="EmailOfRequested" class="control-label"></label>
            <input asp-for="EmailOfRequested" class="form-control" />
            <span asp-validation-for="EmailOfRequested" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <input type="submit" value="Make Auth Request" class="btn btn-primary m-2" />
            <a asp-action="Index" asp-controller="Coach" class="btn btn-secondary m-2">Back to List</a>
        </div>
    </form>
</div>

Bmi.Solution/BMI.Production.SqlLite.WebApp/Views/Coach/RemoveAuth.cshtml
@model BmiUser;
@{
    ViewData["Title"] = "Remove authorization to a user";
}

<h1>Remove authorization to a user</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    <form asp-controller="Coach" asp-action="RemoveAuthUser" method="post">
        <input asp-for="Id" hidden/>
        <button type="submit" class="btn btn-danger">Remove authorization request</button>
        <a asp-controller="Coach" asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

Bmi.Solution/BMI.Production.SqlLite.WebApp/Views/Coach/UserView.cshtml
@model UserViewViewModel;
@inject IBmiRepo BmiRepo;
@{
    ViewData["Title"] = "User BMI log page";
    string weightJson = Model.BmiLogs.ToList().ReturnWeightList().ListToJson();
    string bmiJson = Model.BmiLogs.ToList().ReturnBmiList().ListToJson();
    string emailCoach = BmiRepo.GetById(Model.UserId).Email;
}

@section Style {
    <link href="~/lib/css/chart.css" rel="stylesheet" />
}

<h1 class="text-center">User BMI log list: @emailCoach</h1>
@{
    if (Model != null && Model.BmiLogs.Count() > 0)
    {
        <table class="table row-cols-sm-3">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Lenght</th>
                    <th>Weight</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (BmiLog bmiLog in Model.BmiLogs)
                {
                    <tr>
                        <th>@bmiLog.DateLog.ToShortDateString()</th>
                        <th>@bmiLog.Lenght m</th>
                        <th>@bmiLog.Weight kg</th>
                        <th>
                            <a asp-controller="Coach" asp-action="DetailBmiLogOfUser"
                               asp-route-bmiLogId="@bmiLog.ID" asp-route-userId="@Model.UserId" class="btn-link">Detail</a>
                            @if (User.IsInRole(Roles.Admin))
                            {
                                <a asp-controller="Admin" asp-action="RemoveBmiLog"
                                   asp-route-bmiLogId="@bmiLog.ID" asp-route-userId="@Model.UserId" class="btn-link">Detail</a>
                                <a asp-controller="Admin" asp-action="UpdateBmiLog"
                                   asp-route-bmiLogId="@bmiLog.ID" asp-route-userId="@Model.UserId" class="btn-link">Detail</a>
                            }
                        </th>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <hr />
            <a asp-action="ReturnCsv" asp-controller="Export" asp-route-userId="@Model.UserId">Export CSV file</a>
            <hr />
            <a asp-action="ReturnMd" asp-controller="Export" asp-route-userId="@Model.UserId">Export MD file</a>
            <hr />
        </div>
        <h5 class="card-title text-center">BMI(body mass index) graph</h5>
        <div id="chartBMI" class="ct-chart" data-weight="@Model.BmiLogs.ToList().ReturnBmiList().ListToJson()"></div>
        @section Scripts {
            <script asp-suppress-fallback-integrity="false" src="~/lib/js/ChartBmi.js"></script>
        }
    }
    else
    {
        <h2 class="text-center">@Model.UserId has no BMI logs.</h2>
    }
}